= Ansible Boot Camp Day 2
:navtitle: Home

== Introduction

Welcome to Ansible Boot Camp Day 2. This intensive, hands-on course is designed for students to move from being Ansible Users to Ansible Architects.

The shared goal is to build an automation environment that is repeatable *through Molecule*, secure and curated *through Private Automation Hub*, and highly available *through OpenShift*. You will be equipped to manage the entire lifecycle of automation—from the first line of a test case to the global deployment of a platform.

Duration: 2 hours

== Objectives

On completing this course, you should be able to:

- Learn how to manage your entire Ansible Automation Platform configuration as code using Ansible playbooks.

- Stop "testing in production." Learn to apply software engineering rigors to your infrastructure code using the Molecule framework.

- Leverage the power of container. Discover how to deploy, manage, and scale the Ansible Automation Platform as a native OpenShift application.

== Prerequisites

This course assumes that you have the following prior experience:

- Basic understanding of Git, Linux, OpenShift and Ansible Automation platform. 

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

- Andrew Block (Distinguished Architect)
- Walter Bentley (Senior Manager for Ansible Platform Practice)
- Vinny Valdez (Chief Architect for Automation Domain Specialist)
- Amrinder Singh (Content Architect)
- Anna Swicegood (Learning Product Manager)
